export const restaurantData = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
    dishName: "Margherita Pizza",
    restaurantName: "Pizza Palace",
    cuisineName: ["Italian", "Pizza", "Fast Food", "Beverages"],
    deliveryTime: "25 mins",
    rating: 4.5,
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    dishName: "Veg Burger",
    restaurantName: "Burger Hub",
    cuisineName: ["American", "Burgers", "Snacks", "Fast Food"],
    deliveryTime: "30 mins",
    rating: 4.2,
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
    dishName: "Paneer Butter Masala",
    restaurantName: "Spice Villa",
    cuisineName: ["North Indian", "Punjabi", "Curries", "Desserts"],
    deliveryTime: "35 mins",
    rating: 4.7,
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246",
    dishName: "Hakka Noodles",
    restaurantName: "Wok Express",
    cuisineName: ["Chinese", "Asian", "Noodles", "Street Food"],
    deliveryTime: "20 mins",
    rating: 4.1,
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1611270629569-8b357cb88da9",
    dishName: "Masala Dosa",
    restaurantName: "South Treat",
    cuisineName: ["South Indian", "Dosa", "Breakfast", "Snacks"],
    deliveryTime: "18 mins",
    rating: 4.8,
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    dishName: "Sushi Roll",
    restaurantName: "Tokyo Bites",
    cuisineName: ["Japanese", "Sushi", "Seafood", "Asian"],
    deliveryTime: "40 mins",
    rating: 4.6,
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947",
    dishName: "Grilled Sandwich",
    restaurantName: "Snack Corner",
    cuisineName: ["Cafe", "Sandwiches", "Snacks", "Beverages"],
    deliveryTime: "15 mins",
    rating: 4.0,
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    dishName: "Chocolate Cake",
    restaurantName: "Sweet Oven",
    cuisineName: ["Desserts", "Bakery", "Cakes", "Pastries"],
    deliveryTime: "28 mins",
    rating: 4.9,
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    dishName: "Caesar Salad",
    restaurantName: "Green Bowl",
    cuisineName: ["Healthy", "Salads", "Vegan", "Organic"],
    deliveryTime: "22 mins",
    rating: 4.3,
  },
  {
    id: 10,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    dishName: "Chicken Biryani",
    restaurantName: "Royal Kitchen",
    cuisineName: ["Hyderabadi", "Biryani", "Mughlai", "Indian"],
    deliveryTime: "32 mins",
    rating: 4.8,
  },
  {
    id: 11,
    image: "https://images.unsplash.com/photo-1521389508051-d7ffb5dc8f70",
    dishName: "Tacos",
    restaurantName: "Mexi Fiesta",
    cuisineName: ["Mexican", "Tacos", "Street Food", "Fast Food"],
    deliveryTime: "26 mins",
    rating: 4.4,
  },
  {
    id: 12,
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f",
    dishName: "Pasta Alfredo",
    restaurantName: "Little Italy",
    cuisineName: ["Italian", "Pasta", "Continental", "Cheese"],
    deliveryTime: "29 mins",
    rating: 4.5,
  },
  {
    id: 13,
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759",
    dishName: "Falafel Wrap",
    restaurantName: "Arabian Nights",
    cuisineName: ["Middle Eastern", "Wraps", "Lebanese", "Healthy"],
    deliveryTime: "24 mins",
    rating: 4.2,
  },
  {
    id: 14,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
    dishName: "French Fries",
    restaurantName: "Crunch House",
    cuisineName: ["Snacks", "Fast Food", "Fries", "Beverages"],
    deliveryTime: "12 mins",
    rating: 3.9,
  },
  {
    id: 15,
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543",
    dishName: "Pancakes",
    restaurantName: "Morning Cafe",
    cuisineName: ["Breakfast", "Cafe", "Desserts", "Beverages"],
    deliveryTime: "17 mins",
    rating: 4.6,
  },
];
